"""add order id to stock reservations

Revision ID: 33a7563ffd93
Revises: f19d013e1636
Create Date: 2026-09-17 03:42:36.895135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33a7563ffd93'
down_revision: Union[str, Sequence[str], None] = 'f19d013e1636'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_reservations', sa.Column('order_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'stock_reservations', 'orders', ['order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'stock_reservations', type_='foreignkey')
    op.drop_column('stock_reservations', 'order_id')
    # ### end Alembic commands ###
