"""add restock date to branch stock

Revision ID: eb7b0db299ff
Revises: 7e0c4970ed01
Create Date: 2026-09-17 00:43:25.032353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'eb7b0db299ff'
down_revision: Union[str, Sequence[str], None] = '7e0c4970ed01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branch_stock', sa.Column('restock_date', sa.DateTime(), nullable=True))
    op.alter_column('orders', 'branch_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'branch_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('branch_stock', 'restock_date')
    # ### end Alembic commands ###
