import type { Branch, BranchStock, Order, Product, User } from "./types";

export const DEMO_CREDENTIALS = {
  customer: { email: "customer@demo.com", password: "password123" },
  admin: { email: "admin@demo.com", password: "password123" },
};

export const users: User[] = [
  {
    id: 1,
    name: "Demo Customer",
    email: "customer@demo.com",
    role: "customer",
    status: "active",
    createdAt: "2026-01-12T10:00:00Z",
  },
  {
    id: 2,
    name: "System Admin",
    email: "admin@demo.com",
    role: "admin",
    status: "active",
    createdAt: "2026-01-01T08:00:00Z",
  },
  {
    id: 3,
    name: "Nimal Perera",
    email: "nimal@example.com",
    role: "customer",
    status: "active",
    createdAt: "2026-02-18T14:20:00Z",
  },
  {
    id: 4,
    name: "Sachini Fernando",
    email: "sachini@example.com",
    role: "customer",
    status: "active",
    createdAt: "2026-03-02T09:15:00Z",
  },
  {
    id: 5,
    name: "Ops Admin",
    email: "ops@demo.com",
    role: "admin",
    status: "active",
    createdAt: "2026-01-05T11:00:00Z",
  },
];

export const products: Product[] = [
  {
    id: 1,
    name: "Wireless Headphones",
    description:
      "Noise-cancelling over-ear headphones with 30-hour battery life and Bluetooth 5.3.",
    price: 18900,
    image:
      "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&q=80",
    category: "Electronics",
    active: true,
  },
  {
    id: 2,
    name: "Smart Watch Pro",
    description:
      "Fitness tracking, heart-rate monitor, GPS, and water resistance up to 50m.",
    price: 24500,
    image:
      "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&q=80",
    category: "Electronics",
    active: true,
  },
  {
    id: 3,
    name: "Organic Green Tea",
    description:
      "Premium Ceylon green tea leaves, packed fresh. Box of 50 biodegradable bags.",
    price: 1250,
    image:
      "https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?w=800&q=80",
    category: "Grocery",
    active: true,
  },
  {
    id: 4,
    name: "Cotton T-Shirt",
    description:
      "Soft organic cotton crew-neck tee. Available in multiple sizes. Everyday comfort.",
    price: 2800,
    image:
      "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&q=80",
    category: "Apparel",
    active: true,
  },
  {
    id: 5,
    name: "Ceramic Coffee Mug",
    description:
      "Hand-glazed 350ml mug. Microwave and dishwasher safe. Matte finish.",
    price: 1650,
    image:
      "https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?w=800&q=80",
    category: "Home",
    active: true,
  },
  {
    id: 6,
    name: "Laptop Stand",
    description:
      "Aluminum ergonomic stand with adjustable height and cable management.",
    price: 7200,
    image:
      "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=800&q=80",
    category: "Electronics",
    active: true,
  },
  {
    id: 7,
    name: "Running Shoes",
    description:
      "Lightweight cushioned runners with breathable mesh upper for daily training.",
    price: 11200,
    image:
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80",
    category: "Apparel",
    active: true,
  },
  {
    id: 8,
    name: "Desk Lamp",
    description:
      "LED desk lamp with three brightness levels and USB charging port.",
    price: 4500,
    image:
      "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800&q=80",
    category: "Home",
    active: false,
  },
];

export const branches: Branch[] = [
  {
    id: 1,
    name: "Colombo Fort Branch",
    address: "42 York St, Colombo 01",
    latitude: 6.9344,
    longitude: 79.8428,
    capacity: 40,
    currentWorkload: 18,
    active: true,
  },
  {
    id: 2,
    name: "Kandy City Branch",
    address: "15 Dalada Veediya, Kandy",
    latitude: 7.2936,
    longitude: 80.6413,
    capacity: 30,
    currentWorkload: 22,
    active: true,
  },
  {
    id: 3,
    name: "Galle Face Branch",
    address: "88 Galle Road, Colombo 03",
    latitude: 6.9219,
    longitude: 79.8478,
    capacity: 50,
    currentWorkload: 12,
    active: true,
  },
  {
    id: 4,
    name: "Negombo Branch",
    address: "120 Main Street, Negombo",
    latitude: 7.2083,
    longitude: 79.8358,
    capacity: 25,
    currentWorkload: 8,
    active: false,
  },
];

export const branchStocks: BranchStock[] = [
  { id: 1, branchId: 1, productId: 1, physicalStock: 40, reservedStock: 4 },
  { id: 2, branchId: 1, productId: 2, physicalStock: 25, reservedStock: 2 },
  { id: 3, branchId: 1, productId: 3, physicalStock: 120, reservedStock: 10 },
  { id: 4, branchId: 1, productId: 4, physicalStock: 60, reservedStock: 5 },
  { id: 5, branchId: 1, productId: 5, physicalStock: 35, reservedStock: 0 },
  { id: 6, branchId: 1, productId: 6, physicalStock: 18, reservedStock: 3 },
  { id: 7, branchId: 1, productId: 7, physicalStock: 22, reservedStock: 1 },
  { id: 8, branchId: 2, productId: 1, physicalStock: 15, reservedStock: 2 },
  { id: 9, branchId: 2, productId: 2, physicalStock: 10, reservedStock: 1 },
  { id: 10, branchId: 2, productId: 3, physicalStock: 80, reservedStock: 5 },
  { id: 11, branchId: 2, productId: 4, physicalStock: 40, reservedStock: 0 },
  { id: 12, branchId: 2, productId: 5, physicalStock: 20, reservedStock: 2 },
  { id: 13, branchId: 2, productId: 6, physicalStock: 8, reservedStock: 0 },
  { id: 14, branchId: 2, productId: 7, physicalStock: 12, reservedStock: 0 },
  { id: 15, branchId: 3, productId: 1, physicalStock: 55, reservedStock: 6 },
  { id: 16, branchId: 3, productId: 2, physicalStock: 30, reservedStock: 4 },
  { id: 17, branchId: 3, productId: 3, physicalStock: 95, reservedStock: 8 },
  { id: 18, branchId: 3, productId: 4, physicalStock: 70, reservedStock: 3 },
  { id: 19, branchId: 3, productId: 5, physicalStock: 0, reservedStock: 0 },
  { id: 20, branchId: 3, productId: 6, physicalStock: 28, reservedStock: 2 },
  { id: 21, branchId: 3, productId: 7, physicalStock: 35, reservedStock: 4 },
];

export const orders: Order[] = [
  {
    id: 101,
    orderNumber: "SOA-00101",
    userId: 1,
    customerName: "Demo Customer",
    customerEmail: "customer@demo.com",
    phone: "+94 77 123 4567",
    deliveryAddress: "27 Flower Road, Colombo 07",
    latitude: 6.9022,
    longitude: 79.8607,
    orderNote: "Leave at reception",
    branchId: 3,
    status: "OUT_FOR_DELIVERY",
    paymentMethod: "COD",
    paymentStatus: "PENDING",
    totalAmount: 21700,
    estimatedDeliveryDate: "2026-09-17T14:00:00Z",
    createdAt: "2026-09-15T08:30:00Z",
    items: [
      {
        productId: 1,
        productName: "Wireless Headphones",
        quantity: 1,
        unitPrice: 18900,
      },
      {
        productId: 3,
        productName: "Organic Green Tea",
        quantity: 2,
        unitPrice: 1250,
      },
    ],
    allocation: {
      selectedBranchId: 3,
      distanceKm: 2.4,
      workload: 12,
      distanceScore: 0.92,
      workloadScore: 0.76,
      finalScore: 0.856,
      distanceWeight: 0.6,
      workloadWeight: 0.4,
      eligibleBranches: 2,
    },
  },
  {
    id: 102,
    orderNumber: "SOA-00102",
    userId: 1,
    customerName: "Demo Customer",
    customerEmail: "customer@demo.com",
    phone: "+94 77 123 4567",
    deliveryAddress: "27 Flower Road, Colombo 07",
    latitude: 6.9022,
    longitude: 79.8607,
    branchId: 1,
    status: "DELIVERED",
    paymentMethod: "COD",
    paymentStatus: "PAID",
    totalAmount: 24500,
    estimatedDeliveryDate: "2026-09-10T12:00:00Z",
    createdAt: "2026-09-08T11:00:00Z",
    items: [
      {
        productId: 2,
        productName: "Smart Watch Pro",
        quantity: 1,
        unitPrice: 24500,
      },
    ],
    allocation: {
      selectedBranchId: 1,
      distanceKm: 3.1,
      workload: 18,
      distanceScore: 0.85,
      workloadScore: 0.55,
      finalScore: 0.73,
      distanceWeight: 0.6,
      workloadWeight: 0.4,
      eligibleBranches: 3,
    },
  },
  {
    id: 103,
    orderNumber: "SOA-00103",
    userId: 3,
    customerName: "Nimal Perera",
    customerEmail: "nimal@example.com",
    phone: "+94 71 555 8899",
    deliveryAddress: "9 Temple Road, Kandy",
    latitude: 7.2905,
    longitude: 80.6337,
    branchId: 2,
    status: "PROCESSING",
    paymentMethod: "COD",
    paymentStatus: "PENDING",
    totalAmount: 14000,
    estimatedDeliveryDate: "2026-09-18T10:00:00Z",
    createdAt: "2026-09-15T15:45:00Z",
    items: [
      {
        productId: 4,
        productName: "Cotton T-Shirt",
        quantity: 1,
        unitPrice: 2800,
      },
      {
        productId: 7,
        productName: "Running Shoes",
        quantity: 1,
        unitPrice: 11200,
      },
    ],
    allocation: {
      selectedBranchId: 2,
      distanceKm: 1.2,
      workload: 22,
      distanceScore: 0.96,
      workloadScore: 0.27,
      finalScore: 0.684,
      distanceWeight: 0.6,
      workloadWeight: 0.4,
      eligibleBranches: 1,
    },
  },
  {
    id: 104,
    orderNumber: "SOA-00104",
    userId: 4,
    customerName: "Sachini Fernando",
    customerEmail: "sachini@example.com",
    phone: "+94 76 222 3344",
    deliveryAddress: "55 Marine Drive, Colombo 03",
    latitude: 6.9271,
    longitude: 79.8612,
    branchId: 3,
    status: "ALLOCATED",
    paymentMethod: "COD",
    paymentStatus: "PENDING",
    totalAmount: 7200,
    estimatedDeliveryDate: "2026-09-19T16:00:00Z",
    createdAt: "2026-09-16T07:20:00Z",
    items: [
      {
        productId: 6,
        productName: "Laptop Stand",
        quantity: 1,
        unitPrice: 7200,
      },
    ],
    allocation: {
      selectedBranchId: 3,
      distanceKm: 0.8,
      workload: 12,
      distanceScore: 0.98,
      workloadScore: 0.76,
      finalScore: 0.892,
      distanceWeight: 0.6,
      workloadWeight: 0.4,
      eligibleBranches: 2,
    },
  },
  {
    id: 105,
    orderNumber: "SOA-00105",
    userId: 1,
    customerName: "Demo Customer",
    customerEmail: "customer@demo.com",
    phone: "+94 77 123 4567",
    deliveryAddress: "27 Flower Road, Colombo 07",
    latitude: 6.9022,
    longitude: 79.8607,
    branchId: 1,
    status: "CANCELLED",
    paymentMethod: "COD",
    paymentStatus: "PENDING",
    totalAmount: 1650,
    estimatedDeliveryDate: "2026-09-12T11:00:00Z",
    createdAt: "2026-09-11T09:00:00Z",
    items: [
      {
        productId: 5,
        productName: "Ceramic Coffee Mug",
        quantity: 1,
        unitPrice: 1650,
      },
    ],
  },
];

export const categories = [
  "All",
  "Electronics",
  "Grocery",
  "Apparel",
  "Home",
];

export const activityFeed = [
  {
    id: 1,
    message: "Order SOA-00104 allocated to Galle Face Branch",
    time: "12 min ago",
  },
  {
    id: 2,
    message: "Stock updated: Wireless Headphones at Colombo Fort (+10)",
    time: "45 min ago",
  },
  {
    id: 3,
    message: "Order SOA-00101 marked Out for Delivery",
    time: "1 hr ago",
  },
  {
    id: 4,
    message: "New customer registered: Sachini Fernando",
    time: "3 hr ago",
  },
  {
    id: 5,
    message: "Low stock alert: Ceramic Coffee Mug at Galle Face (0)",
    time: "4 hr ago",
  },
];
